apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Release.Name }}-resourcequota
  namespace: {{ .Release.Namespace }}
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "1280Mi"
    limits.cpu: "2"
    limits.memory: "2Gi"
    pods: "4"
