replicaCount: 2
image:
  repository: jungyungee/ktb-community-backend
  tag: "f69e5e22431a762a1677bef18f4f60fa10935905" # 버전 명시
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
resources:
  requests:
    cpu: 300m
    memory: 384Mi
  limits:
    cpu: 500m
    memory: 512Mi
labels:
  app: ktb-community
  tier: backend
