services:
  backend:
    # 도커 파일로 이미지 생성
    image: jungyungee/ktb-community-backend:${IMAGE_TAG}
    ports:
      - "${HOST_PORT}:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    restart: unless-stopped