name: ktb-community
# 서비스는 논리적인 역할 이름
services:
  backend:
    # 도커 파일로 이미지 생성
    image: ktb-community-backend:1.0.0
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    restart: unless-stopped