spring.application.name=ktb_community
# 로컬 실행 시 프로젝트 루트의 .env 파일을 환경 설정으로 불러옴
spring.config.import=optional:file:.env[.properties]
server.servlet.context-path=/server-api
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

spring.jpa.hibernate.ddl-auto=update
#logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.orm.jdbc.bind=trace
#spring.jpa.properties.hibernate.generate_statistics=true
#logging.level.org.hibernate.stat=debug

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
jwt.secret=${JWT_SECRET}

aws.region=ap-southeast-2
aws.s3.bucket=ktb-community-image-s3-419407685035-ap-southeast-2-an
# Presigned URL 유효 시간(초)
aws.s3.presigned-url-expiration-seconds=300
