spring.application.name=ktb_community
server.servlet.context-path=/server-api
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace
spring.jpa.properties.hibernate.generate_statistics=true
logging.level.org.hibernate.stat=debug

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
jwt.secret=${JWT_SECRET}

aws.region=ap-southeast-2
aws.s3.bucket=ktb-community-image-s3-419407685035-ap-southeast-2-an