# ci.yml
name: Backend CI

on:
  # PR 에서 CI
  pull_request:
    branches:
      - dev
      - main
  # dev -> main merge 시 도커 이미지 push (실제 배포는 ArgoCD에서)
  push:
    branches:
      - main
  # 수동 작업
  workflow_dispatch:

jobs:
  # 테스트 코드는 추후에 추가 예정
  # 빌드 및 헬스 체크
  ci:
    runs-on: ubuntu-latest
    steps:
      # 깃허브 러너에 저장소를 클론
      - name: checkout repository
        uses: actions/checkout@v6
      # - 테스트 코드 작성 후 gradle Test 추가 필요
      # - jdk set up
      # - gradle test

      # 이미지 빌드 - Docker Buildx와 GitHub Actions 캐시 사용
      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: image build
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ktb-community-backend:${{ github.sha }}
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 만들어진 이미지로 도커 run (도커 컴포즈 사용)
      - name: docker run
        run: IMAGE_TAG=${{ github.sha }} docker compose -f compose.ci.yml up -d

      # 헬스체크
      - name: health check
        run: |
          for i in {1..10}; do
            if curl -f http://localhost:8080/server-api/health; then
              echo "Health Check Success"
              exit 0
            fi
          
            echo "Waiting ($i/10)"
            sleep 5
          done
          
          echo "Health Check Failed"
          docker compose -f compose.ci.yml logs backend
          exit 1

      # 도커 허브 로그인
      - name: docker hub login
        if: |
          (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
          github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 도커 이미지에 태그 붙이기
      - name: tag docker image
        if: |
          (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
          github.event_name == 'workflow_dispatch'
        run: |
          docker tag \
            ktb-community-backend:${{ github.sha }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/ktb-community-backend:${{ github.sha }}

      # 도커 이미지 푸시
      - name: push docker image
        if: |
          (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
          github.event_name == 'workflow_dispatch'
        run: |
          docker push \
            ${{ secrets.DOCKERHUB_USERNAME }}/ktb-community-backend:${{ github.sha }}